### ISSUE TITLE
How is lay encoder connected to fine meaning decoder?

### ISSUE THREAD

**Issue by Sandy26** [donglixp/coarse2fine#11]
Hi Mr. Li,
According to the paper(Fig 3) sketch encoding is connected to cond_decoder in the neural net.

But in Models.py line 440: lay_out = self.lay_classifier(q_ht)  
after getting the output of lay classifier-> lay_out, lay_out is not used in the rest of the function for decoding conditions. Then how can we say that encoded layout is connected to condition decoder?

Also for lay classifier you used [lay.vocab()](https://github.com/donglixp/coarse2fine/blob/8d135d04ce16107e913028212c4df615a3940d7f/wikisql/table/ModelConstructor.py#L108) but for lay_encoder you used [cond_op.vocab.](https://github.com/donglixp/coarse2fine/blob/8d135d04ce16107e913028212c4df615a3940d7f/wikisql/table/ModelConstructor.py#L115) Both fields hold the same value. Any particular for using these different field names?

Thank you,
Shruti

**Comment by donglixp** [comment]
During inference, they are used in https://github.com/donglixp/coarse2fine/blob/master/wikisql/table/Translator.py#L68
