### ISSUE TITLE
GEO and ATIS results

### ISSUE THREAD

**Issue by todpole3** [donglixp/coarse2fine#15]
Hi Li,

I run the code myself and reproduced the results on Django and WikiSQL without any problem.

However, I wasn't able to reproduce the results on GEO and ATIS by running the commands given.

I got acc 86.4 on GEO and 86.2 on ATIS. Would you please take a look at this issue? Thanks.

**Comment by donglixp** [comment]
Hi @todpole3 ,

I am wondering whether they are the results of pre-trained models, or new models?

```bash
./pretrain.sh geoqueries 1
./pretrain.sh atis 1
```

Thanks!

**Comment by todpole3** [comment]
They are the results of the new models:

./run geoqueries 1
./run atis 1

I have tried the pretrained models and their output matched those in the paper.

**Comment by donglixp** [comment]
I tried to run the script ./run.sh, and it works fine. There might be some fluctuations due to the difference of the used environments, as the size of these two datasets is not that large. The results on Django and WikiSQL should be more robust. Thanks!

**Comment by todpole3** [comment]
I see. Thanks for taking a look at this.
