### ISSUE TITLE
data processing issue

### ISSUE THREAD

**Issue by zhuang-li** [donglixp/coarse2fine#24]
Hi Dong,

I am new to the semantic parsing research. But I have several issues related to your dataset. 

I see in the "geoquery" dataset, you replaced the entity with numbers. Wouldn't that be a problem when comparing with other works as I see most works would just keep the entity in the utterance? 

And where do you get the geoquery data annotated with the lambda meaning representation? I searched online and found most works use the geo data annotated with something like "( A , ( _capital ( A ) , _loc ( A , B ) , _const ( B , _stateid ( Iowa ) ) ) )". The two datasets, though, have the same utterance but with different types of annotations.

Thanks if you can resolve these issues for me.

**Comment by donglixp** [comment]
Hi @zhuang-li ,

The argument identification step is deterministic. So we can recover them back to entities deterministically (sec3.6 in https://aclweb.org/anthology/P16-1004 ).
