### ISSUE TITLE
error in preprocess.py

### ISSUE THREAD

**Issue by Sandy26** [donglixp/coarse2fine#3]
Hello,

I am trying to run wikisql/preprocess.py and I get the error-
  File "/home/coarse2fine/wikisql/table/ModelConstructor.py", line 13, in <module>
    from lib.query import agg_ops, cond_ops
When I looked in query.py-agg_ops and cond_ops are lists, how can we "import" lists?or am I misunderstanding something? Actually I could not find "lib" module in your repository hence i am using the one in WIKISQL(https://github.com/salesforce/WikiSQL) Is your query.py difference than the WikiSQL one?

Thank you,
Shruti

**Comment by donglixp** [comment]
Hi @Sandy26 ,

Thanks for the issue. The 'lib' folder is in the default github '.gitignore' file, which made the folder ignored by git. I have removed that line from '.gitignore' and pushed the 'lib' folder. Thanks!

Li
