### ISSUE TITLE
Understanding cond_span_l, cond_span_r and lay fields

### ISSUE THREAD

**Issue by Sandy26** [donglixp/coarse2fine#5]
Hi Li,Stephen

Could you please shed some light on cond_span_l, cond_span_r and lay fields as to what they are used for and how are they modelled(classifier or rnn etc) ? I would like to use the way the in which condition value is predicted for predicting LIMIT value. 

Any insights would be greatly helpful!

Thank you,
Shruti

**Comment by donglixp** [comment]
Hi Shruti,

Each condition value is a text span extracted from the input question. cond_span_l/r is the index of the first/last token of the text span.

They are predicted as shown in the following two lines:
https://github.com/donglixp/coarse2fine/blob/8d135d04ce16107e913028212c4df615a3940d7f/wikisql/table/Translator.py#L110
https://github.com/donglixp/coarse2fine/blob/8d135d04ce16107e913028212c4df615a3940d7f/wikisql/table/Translator.py#L115

The details are described in Page 7 of http://aclweb.org/anthology/P18-1068.pdf .

Best,
Li

**Comment by Sandy26** [comment]
Thank you very much Li. That was indeed helpful!
