### ISSUE TITLE
use of lstm units in encoder

### ISSUE THREAD

**Issue by Sandy26** [donglixp/coarse2fine#6]
Hi Li,

In the paper you mention that you used a bidirectional encoder with LSTM units for encoding inputs. But I do not see anything like say  -> lstm = nn.LSTM(3, 3)  in the code. Am I missing something?

Thank you,
Shruti

**Comment by donglixp** [comment]
https://github.com/donglixp/coarse2fine/blob/master/wikisql/table/ModelConstructor.py#L94

The variable rnn_type is defined in:
https://github.com/donglixp/coarse2fine/blob/8d135d04ce16107e913028212c4df615a3940d7f/wikisql/opts.py#L33

**Comment by Sandy26** [comment]
Thanks Li ! This helped clarify my confusion.
