### ISSUE TITLE
Segmentation fault      (core dumped)

### ISSUE THREAD

**Issue by KeSyren** [donglixp/coarse2fine#9]
Hi Li,

Could you provide me with the Pytorch version in your project? I have a segmentation fault when running the code.

![image](https://user-images.githubusercontent.com/6985499/43049094-07758106-8dc0-11e8-81bc-603dee986a39.png)

**Comment by donglixp** [comment]
Please find the PyTorch version in https://github.com/donglixp/coarse2fine/blob/master/README.md .
